name: effect_bloc
description: BLoC (Business Logic Component) library wrapper with the side effect support.
version: 0.0.1
homepage: https://github.com/allbrightio/effect_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  bloc: ^7.0.0

dev_dependencies:
  test: ^1.16.0
  lint: ^1.5.3
