name: effect_bloc_test
description: Flutter widgets used by the effect_bloc library which supports bloc patter with side effects.
version: 0.0.2
homepage: https://github.com/allbrightio/effect_bloc/packages/effect_bloc_test

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.7.0
  bloc: ^8.0.2

dev_dependencies:
  test: ^1.20.1
  lint: ^1.8.2
