name: flutter_effect_bloc
description: flutter_effect_bloc
version: 0.0.1
homepage: https://github.com/allbrightio/packages/flutter_effect_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  effect_bloc: ^0.0.1
  flutter_bloc:
    git:
      url: https://github.com/allbrightio/bloc
      path: packages/flutter_bloc
      ref: gocal/bloc_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

dependency_overrides:
  effect_bloc:
    path: ../effect_bloc/
  bloc:
    git:
      url: https://github.com/allbrightio/bloc
      path: packages/bloc
      ref: gocal/bloc_interface
