name: flutter_effect_bloc
description: flutter_effect_bloc
version: 0.0.1
author: Marek Gocał <marek@allbright.io>
homepage: https://github.com/allbrightio/effect_bloc

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  effect_bloc: ^0.0.1
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  effect_bloc:
    path: ../effect_bloc/
