name: flutter_effect_bloc
description: flutter_effect_bloc
version: 0.0.2
homepage: https://github.com/allbrightio/packages/flutter_effect_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  effect_bloc: ^0.0.1
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

dependency_overrides:
  effect_bloc:
    path: ../effect_bloc/
